name: Guhca
version: '${project.version}'
main: net.tnn1nja.guhca.Main
api-version: '1.21.5'
authors: [ tnn1nja ]
description: Custom Plugin for Multiplayer UHC.
commands:
  lastplayed:
    description: Shows when player was last online.
    usage: /<command> [player]
    aliases: [ lp ]
  kick:
    description: A proxy for the native kick command.
    usage: /<command> [player] [reason]
  leave:
    description: Leave for a custom reason.
    usage: /<command> [reason]
  playtime:
    description: Shows total playtime of all players.
    usage: /<command>
    aliases: [ pt ]
  damage:
    description: Shows player damage scoreboard.
    usage: /<command>
  nightvision:
    description: Gives the player Night Vision if they have died.
    usage: /<command>
    aliases: [ nv ]
  dimension:
    description: Move between dimensions in Spectator Mode.
    usage: /<command> [dimension]
    aliases: [ dim ]