name: Guhca
version: '${project.version}'
main: net.tnn1nja.guhca.Main
api-version: '1.21'
authors: [ tnn1nja ]
description: Custom Plugin for Multiplayer UHC.
commands:
  lastplayed:
    description: Shows when player was last online.
    usage: /<command>
    aliases: [ lp ]
  kick:
    description: A proxy for the native kick command.
    usage: /<command>
  playtime:
    description: Shows total playtime of all players.
    usage: /<command>
    aliases: [ pt ]
  damage:
    description: Shows player damage scoreboard.
    usage: /<command>