name: Guhca
version: '${project.version}'
main: net.tnn1nja.guhca.Main
api-version: '1.20'
authors: [ tnn1nja ]
description: Custom Plugin for Multiplayer UHC
commands:
  lastplayed:
    description: When player was last online
    usage: /<command>
  lp:
    description: Shorthand for '/lastplayed'
    usage: /<command>
  kick:
    description: A proxy for the native kick command
    usage: /<command>
  playtime:
    description: Shows total playtime of all players.
    usage: /<command>
  pt:
    description: Shorthand for '/playtime'
    usage: /<command>
