name: Guhca
version: '${project.version}'
main: net.tnn1nja.guhca.Main
api-version: '1.21'
authors: [ tnn1nja ]
description: Custom Plugin for Multiplayer UHC.
commands:
  lastplayed:
    description: When player was last online.
    usage: /<command>
  lp:
    description: Shorthand for '/lastplayed'.
    usage: /<command>
  kick:
    description: A proxy for the native kick command.
    usage: /<command>
  playtime:
    description: Shows total playtime of all players.
    usage: /<command>
  pt:
    description: Shorthand for '/playtime'.
    usage: /<command>
  damage:
    description: Shows an ordered list of how much damage each player has taken.
    usage: /<command>
  deaths:
    description: Shows an ordered list of how many times each player has died.
    usage: /<command>
  nightvision:
    description: Gives the player Night Vision if they have died.
    usage: /<command>
  nv:
    description: Shorthand for '/nightvision'/
    usage: /<command>
  dimension:
    description: Move between dimensions in Spectator Mode.
    usage: /<command> [dimension]